### ISSUE TITLE
Goal pages

### ISSUE THREAD

**Issue by ndarville** [ndarville/goal-tracker#8]
Naming options:
- Number ID (included in YAML)
- Shorturl (included in YAML)

**Comment by ndarville** [comment]
## Code

### `_config.yml`

``` yml
collections:
    goals:
        output: true
        permalink: /goal/:path/index.html
        defaults:
            scope:
                path: ""
                type: collection
            values:
                layout: goal # Dun work
```

### `wip.yml` etc

``` yml
- short: Transparent pollution data
  topic: Environment
  slug: pollution-data
```

### `index.html`

``` liquid
{% for goal in goals[type] %}{% if goal.topic == topic %}
    <tr class="{{ type }}">
{% if goal.slug %}
        <td><a href="/goal/{{ goal.slug }}">{{ goal.short }}</a></td>
{% else %}
        <td><a>{{ goal.short }}</a></td>
{% endif %}
        <td>{{ type }}</td>
    </tr>
{% endif %}{% endfor %}
```
- [ ] Have to define the folder somewhere to use it as a config variable.

### `_goals/pollution-data.markdown`

``` liquid
---
layout: goal
---
```
- [ ] No way to import this either—like the folder name from `_config.yml`
